export const providerValues =  { 
    location: { latitude: 39.867311, longitude: -84.137995 },
    lunch: [],
    setLunch: jest.fn(),
    setLocation: jest.fn(),
    distance: 0,
    setDistance: jest.fn(),
    priceRange: [],
    setPriceRange: jest.fn(),
    page: 1,
    setPage: jest.fn(),
    isModalOpen: false,
    setIsModalOpen: jest.fn(),
    isFilterDrawerOpen: false,
    setIsFilterDrawerOpen: jest.fn(),
    loading: false,
    setLoading: jest.fn(),
    isScrolling: false,
    setIsScrolling: jest.fn(),
    };